public class BillingAddressJSONParser {
	public cls_attributes attributes;
    public cls_BillingStreet BillingStreet {get;set;}
	public cls_BillingCity BillingCity;
	public cls_BillingState BillingState;
	public cls_BillingPostalCode BillingPostalCode;
	public cls_BillingCountry BillingCountry;
	public String Id;	//0017F00001bgSaGQAU
	class cls_attributes {
		public String type;	//Account
		public String url;	///services/data/v20.0/sobjects/Account/0017F00001bgSaGQAU
	}
	class cls_BillingStreet {
	}
	class cls_BillingCity {
	}
	class cls_BillingState {
	}
	class cls_BillingPostalCode {
	}
	class cls_BillingCountry {
	}
	
	
}